# site info
title:                재빅의 블로그
tagline:             'for data science & data engineering'
description:         '나의 모든 사람들의 행복을 위하여 끊임없이 노력하기!'
url:                 https://koni114.github.io
logo:                'public/logo.png' 
encoding:            utf-8

plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0


# About/contact
author:
  name:              JaeHun Huh
  description:       '나의 모든 사람들의 행복을 위하여 끊임없이 노력하기!' # main 글귀
  gravatar:          bcf284601785bd2fa85f7001f84a6b34 # md5 hash of your email address
  contact: 
    #linkedin:  <hide>
    github:         https://github.com/koni114
    #facebook:  <hide>
    #twitter:  <hide>
    #weibo:    <hide>
    email:          mailto:swallow9212@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:   # 'tab명': '/blog/tag명.html'        
    - '/blog/'
    #- { Categories: '/blog/categories/' }
    #- { Tags: '/blog/tags/' }
    - { R: '/blog/R/' }               
    - { Python: '/blog/Python/' }
    - { Statistics & Analysis: '/blog/Process/' }
    - { Algorithm: '/blog/Algorithm/' }        
    - { Data engineering: '/blog/Engineering/' }   
    - { Tip: '/blog/Tip/'} 
    - { This And That: '/blog/ThisAndThat/'}
  About:          
    - '/about/'

tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image:   https://koni114.github.io/public/img/apple_and_orange.jpg
  caption: Paul Cesanne, Apples and Oranges

# plugin
mathjax: true # whether support mathjax
google_analytics_id: #UA-XXXX-Y
