# site info
title:               재빅의 블로그
tagline:             'for data science'
description:         'Blog for my growths'
url:                 https://koni114.github.io
logo:                'public/logo.png' 
encoding:            utf-8
baseurl:             ''
remote_theme:        poole/lanyon

# site config
gems:
  - jekyll-paginate
paginate:            5      
permalink:           pretty
version:             1.1.0

# About/contact
author:
  name:              Jaebig
  email:             swallow9212@gmail.com

hero:
  image:   https://koni114.github.io/public/img/apple_and_orange.jpg
  caption: Paul Cesanne, Apples and Oranges


# plugin
mathjax: true # whether support mathjax
plugins:
  - jekyll-paginate
google_analytics_id: #UA-XXXX-Y
