# site info
title:               재빅의 블로그
tagline:             ''
description:        'Blog for my growth'
url:                 http://koni114.github.io
logo:                'public/logo.png' 
encoding:            utf-8
baseurl:             ''
remote_theme:        poole/lanyon

# site config
gems:
  - jekyll-paginate
paginate:            5
permalink:           pretty
version:             1.1.0

# About/contact
author:
  name:              Jaebig
  email:             swallow9212@gmail.com

hero:
  image: https://github.com/koni114/koni114.github.io/blob/master/public/img/apple_and_orange.jpg
  caption: Paul Cesanne, Apples and Oranges


# Gems
plugins:
  - jekyll-paginate
google_analytics_id: #UA-XXXX-Y
